### ISSUE TITLE
I can't get it to work

### ISSUE THREAD

**Issue by FeuSalamander** [WiIIiam278/PAPIProxyBridge#23] opened 2023-04-10 14:30 UTC
I am creating a plugin which is a Global chat plugin for velocity with luckperms support and PAPI.
For the PAPI support I wanted to use your plugin but when I test my code it doesn't work.
For the tests I have my plugin and yours on my velocity server and on the back end I have yours and PAPI
When a player send a message my code is run and it calls that fonction( that fonction is weird cause of the tests)
```java
private String placeholder(String message, final Player player){
        if(placeholderAPI == null)return message;
        UUID p = player.getUniqueId();
        AtomicReference<String> formated = new AtomicReference<>("");
        placeholderAPI.formatPlaceholders("Hello %player_name%!", p).thenAccept(formatedd -> {proxyServer.sendMessage(Component.text("test: "+formatedd));});
        return formated.get();
    }
``` 
And at the end, the message which contains the 'formatedd' variable is "test: Hello %player_name%!" and not the formatted message
(I have the 'player' PAPI ecloud addon)
Thank you for your future reply

**Comment by WiIIiam278** [comment] 2023-04-10 16:58
Hm, perhaps try a different placeholder that doesn't require an expansion, and make sure the user is online and connected _via_ the proxy? Verify that the expansion parses normally with `/papi parse Hello %player_name%` too, to make sure it's not my plugin

Btw that method will always return "" as you're #get()-ing the current String immediately after declaring it; you'll need to change the method to return a future and rework a bit of logic

**Comment by FeuSalamander** [comment] 2023-04-10 17:05
I know that my function will always return "", but for the tests I didn't reworked in it and I already did the command `/papi parse`
And the player is connected because the function is called when I send a message and this is why it's weird

**Comment by WiIIiam278** [comment] 2023-04-10 17:09
how are you depending on the plugin in gradle/maven?

**Comment by FeuSalamander** [comment] 2023-04-10 17:11
maven

**Comment by FeuSalamander** [comment] 2023-04-10 19:17
I dont have "scope" I only have
groupId, artifactId and version.
Do you think this it's the cause of my problem ?

**Comment by WiIIiam278** [comment] 2023-04-10 19:24
Could be. Try it

**Comment by FeuSalamander** [comment] 2023-04-11 10:03
I added `<scope>provided</scope>` but it still not working :(

**Comment by WiIIiam278** [comment] 2023-06-12 13:13
I'm not really able to reproduce this despite best efforts and know others _are_ -- I'm going to close this question out for now since it's been several months. If you need more help, do feel free to keep asking and I'll do my best to try and reply, but I do think there's something up likely with your project or test environment setup causing this to not work for you :)

**Closed by WiIIiam278** 2023-06-12 13:13 UTC
Labels: type: question
